
# package 'arch-install-scripts'
package 'bind-tools'
package 'btrfs-progs'
package 'cmake'
# package 'boost'
package 'dialog'
package 'dosfstools'
package 'doxygen'
package 'expect'
# package 'gcc-fortran'
# package 'gendesk'
package 'gnuplot'
package 'htop'
package 'jq'
package_sp 'lorem-ipsum-generator'
# package 'moreutils'
# package 'net-tools'
# package 'open-jtalk'
# package 'open-jtalk-voice-mei'
package 'pacman-contrib'
package 'patch'
# package 'pcmciautils'
# package 'proot'
package 'qemu'
package 'rlwrap'
package 'rsync'
package 'traceroute'
package 'trash-cli'
package 'tree'
package 'wget'
package 'xsel'


