scrolling:
    history: 50000
    
font:
  normal:
    family: Migu 1M
    style: Regular
  bold:
    family: Migu 1M
    style: Bold
  italic:
    family: Migu 1M

key_bindings:
  - { key:    At,   mods: Control, action: IncreaseFontSize             }
    
