# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Migu 1M
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Migu 1M
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Migu 1M
    # Style can be specified to pick a specific face.
    # style: Italic
