# pacman base-devel group

package 'autoconf'
package 'automake'
package 'binutils'
package 'bison'
package 'fakeroot'
package 'file'
package 'findutils'
package 'flex'
package 'gawk'
package 'gcc'
package 'gettext'
package 'grep'
package 'groff'
package 'gzip'
package 'libtool'
package 'm4'
package 'make'
package 'pacman'
package 'patch'
package 'pkgconf'
package 'sed'
package 'sudo'
package 'systemd'
package 'texinfo'
package 'util-linux'
package 'which'
