# pacman base group

package 'linux'
package 'bash'
package 'bzip2'
package 'coreutils'
package 'cryptsetup'
package 'device-mapper'
# package 'dhcpcd'
package 'diffutils'
package 'e2fsprogs'
package 'file'
package 'filesystem'
package 'findutils'
package 'gawk'
package 'gcc-libs'
package 'gettext'
package 'glibc'
package 'grep'
package 'gzip'
package 'inetutils'
package 'iproute2'
package 'iputils'
package 'jfsutils'
package 'less'
package 'licenses'
package 'logrotate'
package 'lvm2'
package 'man-db'
package 'man-pages'
package 'mdadm'
# package 'nano'
package 'netctl'
package 'pacman'
package 'pciutils'
package 'perl'
package 'procps-ng'
package 'psmisc'
package 'reiserfsprogs'
package 's-nail'
package 'sed'
package 'shadow'
package 'sysfsutils'
package 'systemd-sysvcompat'
package 'tar'
package 'texinfo'
package 'usbutils'
package 'util-linux'
# package 'vi'
package 'which'
package 'xfsprogs'

execute "add multilib to pacman.conf" do
	not_if 'cat /etc/pacman.conf | sed -e "/^#/d" | grep -q "[multilub]"'
	command '/bin/echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf && pacman -Sy'
end

